from selenium.webdriver.common.by import By
from settings.setting_data_info import data_info


class DrrpStatementLocator:
    sub_menu_create_statement = (By.XPATH, '//span[text()="Реєстрація заяви"]')
    sub_sub_menu_statement = {
        'ownership': (By.XPATH, '//span[text()="заява про реєстрацію права власності"]/..'),
        # 'irp': (By.XPATH, '//span[text()="заява про реєстрацію іншого речового права"]/..'),
        # 'encumbrances': (By.XPATH, '//span[text()="заява про реєстрацію обтяження"]/..'),
        # 'relinquishment_of_property': (By.XPATH, '//span[text()="заява про відмову від речового права"]/..')
    }
    block_common_info = (By.XPATH, '//span[text()="Відомості"]/..')
    kind_registration = (By.CSS_SELECTOR, 'input[name$="EntityChangeTypeBit"]')
    kind_registration_list = (
        By.XPATH,
        '//ul/li[text()="{kind_registration}"]'.format(kind_registration=data_info['onm']['kind_registration']))
    num_ownership = (By.CSS_SELECTOR, 'input[name="enum"]')
    form_ownership = (By.CSS_SELECTOR, 'input[name$="PrType"]')
    form_ownership_list = (
        By.XPATH, '//ul/li[text()="{form_ownership}"]'.format(form_ownership=data_info['onm']['form_ownership']))
    kind_common_ownership = (By.CSS_SELECTOR, 'input[name$="CommonKind"]')
    kind_common_ownership_list = (By.XPATH, '//ul/li[text()="{kind_common_ownership}"]'.format(
        kind_common_ownership=data_info['onm']['kind_common_ownership']))
    kind_common_ownership_list_edit = (By.XPATH, '//ul/li[text()="{kind_common_ownership_edit}"]'.format(
        kind_common_ownership_edit=data_info['onm']['kind_common_ownership_edit']))
    block_onm = (By.XPATH, '//span[text()="Об’єкти нерухомого майна"]/..')
    block_add_onm = (By.XPATH, '//span[text()="Додати ОНМ"]/..')
    type_onm = (By.CSS_SELECTOR, 'input[name$="ReType"]')
    type_onm_list = (By.XPATH, '//ul/li[text()="квартира"]')
    type_onm_list_ground = (By.XPATH, '//ul/li[text()="земельна ділянка"]')
    cad_num_onm = (By.CSS_SELECTOR, 'input[name="cadNum"]')
    btn_get_info_dzk = (By.CSS_SELECTOR, 'a[data-qtip="Отримати відомості з ДЗК"]')
    addition_of_type_onm = (By.CSS_SELECTOR, 'input[name$="TypeExtension"]')
    subtype_onm = (By.CSS_SELECTOR, 'input[name$="ReSubType"]')
    subtype_onm_list = (By.XPATH, '//ul/li[text()="{subtype_onm}"]'.format(subtype_onm=data_info['onm']['subtype_onm']))
    addition_of_subtype_onm = (By.CSS_SELECTOR, 'input[name$="SubTypeExtension"]')
    description_onm = (By.CSS_SELECTOR, 'textarea[name="description"]')
    block_add_address_onm = (By.XPATH, '//span[text()="Додати адресу ОНМ"]/..')
    address_onm_locality = (By.CSS_SELECTOR, 'input[name="ATU_ATU_ID"]')
    address_onm_locality_list = (By.CSS_SELECTOR, '.combo-search-match')
    address_onm_street = (By.CSS_SELECTOR, 'input[name="streetName"]')
    address_onm_street_list = (By.XPATH, '//ul/li/span[text()="{address_onm_street}"]'.format(
        address_onm_street=data_info['address_onm']['address_onm_street']))
    house_type = (By.CSS_SELECTOR, 'input[name$="HouseType"]')
    building_type = (By.CSS_SELECTOR, 'input[name$="BuildingType"]')
    house_type_list = (By.XPATH, '//ul/li/span[text()="будинок"]/..')
    house_num = (By.CSS_SELECTOR, 'input[name="house"]')
    building_type_list = (By.XPATH, '//ul/li/span[text()="корп."]')
    building_num = (By.CSS_SELECTOR, 'input[name="building"]')
    object_num_type = (By.CSS_SELECTOR, 'input[name$="ObjectNumType"]')
    object_num_type_list = (By.XPATH, '//ul/li/span[text()="квартира"]')
    object_num = (By.CSS_SELECTOR, 'input[name="objectNum"]')
    addition_of_address_onm = (By.CSS_SELECTOR, 'textarea[name="additional"]')
    person_type = (By.XPATH, '//span[text()="Фізична особа"]/..')
    person_rule = (By.CSS_SELECTOR, 'input[name$="SbjRlNameBit"]')
    person_rule_list = (By.XPATH, '//ul/li[text()="Заявник"]')
    person_name = (By.CSS_SELECTOR, 'input[name="sbjName"]')
    person_code = (By.CSS_SELECTOR, 'input[name="sbjCode"]')
    person_phone = (By.CSS_SELECTOR, 'input[name="phone"]')
    passport_series = (By.CSS_SELECTOR, 'input[name="passportSeriesNum"]')
    passport_date = (By.CSS_SELECTOR, 'input[name="docDate"]')
    passport_publisher = (By.CSS_SELECTOR, 'input[name="publisher"]')
    addition_of_person = (By.CSS_SELECTOR, 'textarea[name="additional"]')
    payment_block = (By.XPATH, '//span[text()="Реквізити оплати"]/..')
    payment_type = (By.CSS_SELECTOR, 'input[name$="PayType"]')
    payment_type_list = (By.XPATH, '//ul/li[text()="Адміністративний збір за реєстраційні дії"]')
    payment_num = (By.CSS_SELECTOR, 'input[name="enum"]')
    payment_date = (By.CSS_SELECTOR, 'input[name$="rpdDate"]')
    payment_summ = (By.CSS_SELECTOR, 'input[name="summ"]')
    org_name = (By.CSS_SELECTOR, 'input[name="orgName"]')
    document_type = (By.CSS_SELECTOR, 'input[name$="CdType"]')
    document_type_list = (By.XPATH, '//span[text()="договір іпотеки"]')
    document_type_dabi = (By.XPATH, '//span[text()="сертифікат ДАБІ"]')
    document_type_edrsr = (By.XPATH, '//span[text()="рішення суду"]')
    addition_document_type = (By.CSS_SELECTOR, 'input[name="cdTypeExtension"]')
    document_num = (By.CSS_SELECTOR, 'input[name="enum"]')
    document_date = (By.CSS_SELECTOR, 'input[name="docDate"]')
    document_publisher = (By.CSS_SELECTOR, 'input[name="publisher"]')
    document_count_page = (By.CSS_SELECTOR, 'input[name="countPages"]')
    statement_num = (By.CSS_SELECTOR, 'input[name="outNum"]')
    statement_date = (By.CSS_SELECTOR, 'input[name="outDate"]')
    statement_term_review = (By.CSS_SELECTOR, 'input[name$="TermReview"]')
    statement_term_review_list = (By.XPATH, '//ul/li[text()="2 робочі дні"]')
    statement_receive_type = (By.CSS_SELECTOR, 'input[name$="DocReceiveType"]')
    statement_receive_type_list = (By.XPATH, '//ul/li[text()="особисто"]')
    addition_of_statement = (By.CSS_SELECTOR, 'textarea[name="additional"]')
    ubdocument = (By.CSS_SELECTOR, 'div[id^="ubdocument"]')
    field_type_irp = (By.CSS_SELECTOR, 'input[name$="IrpSortReq"]')
    field_type_irp_list = (By.XPATH, '//li[text()="{type_irp}"]'.format(type_irp=data_info['onm']['type_irp']))
    addition_type_irp = (By.CSS_SELECTOR, 'input[name="irpPrTypeExtension"]')
    field_type_encumbrances = (By.CSS_SELECTOR, 'input[name$="LmType"]')
    type_encumbrances_list = (By.XPATH, '//li[text()="іпотека"]')
    checkbox = (By.CSS_SELECTOR, 'input[role="checkbox"]')
    type_ownership = (By.CSS_SELECTOR, 'input[name$="EnumType"]')
    type_ownership_list = (By.XPATH, '//li[text()="Інше речове право"]')
    type_another_property_right = (By.CSS_SELECTOR, 'input[name$="IrpSortReq"]')
    type_another_property_right_list = (By.XPATH, '//li[text()="{type_another_property_right}"]'.format(
        type_another_property_right=data_info['common_info']['type_another_property_right']))
    statement_status = (By.XPATH, '//*[text()="зареєстровано"]')
    form_edit_statement_field_reason = (By.CSS_SELECTOR, 'textarea[name="reason"]')
    form_edit_statement_button_edit = (By.XPATH, '//span[text()="Редагувати"]')
    operations_tab_menu = (By.XPATH, '//span[text()="Операції"]/..')
    form_edit_statement_undo_last_action = (By.XPATH, '//span[text()="Відмінити останню операцію"]')
    form_edit_statement_button_undo_last_action = (By.XPATH, '//span[text()="Відмінити останню операцію"]')
    data_qtip_undo_last_action = (By.CSS_SELECTOR, 'td[data-qtip="Відміна помилкової  операції із заявою"]')
    form_edit_statement_decision = (By.XPATH, '//span[text()="Рішення"]')
    decision_sub_menu_make_decision = (By.XPATH, '//span[text()="Прийняти рішення про державну реєстрацію"]')
    payment_btn_plus = (By.CLASS_NAME, 'fa-plus-circle')
    li_is_opened = (By.CLASS_NAME, "is-opened")
    span_get_erd = (By.XPATH, '//span[text()="Отримати з ЄРД"]/..')
    get_edrsr = (By.XPATH, '//*[node()="Запит до ЄДРСР"]/../..')
    sub_menu_create_queue_statement = (By.XPATH, '//span[text()="Черга заяв, поданих в електронній формі"]')

class DrrpFormRequestEdrsrLocator:
    form_request_edrsr = (By.XPATH, '//span[text()="Запит до ЄДРСР"]')
    form_request_edrsr_date = (By.CSS_SELECTOR, 'input[name="docDate"]')
    form_request_edrsr_num = (By.CSS_SELECTOR, 'input[name="caseNum"]')
    form_request_edrsr_name_court = (By.CSS_SELECTOR, 'input[name="courtID"]')
    form_request_edrsr_type_doc = (By.CSS_SELECTOR, 'input[name="docTypeID"]')
